export const PRODUCTS_ACTION = {
  GET_ALL_PRODUCTS_BEGIN: 'GET_ALL_PRODUCTS_BEGIN',
  GET_ALL_PRODUCTS_FULFILLED: 'GET_ALL_PRODUCTS_FULFILLED',
  GET_ALL_PRODUCTS_REJECTED: 'GET_ALL_PRODUCTS_REJECTED',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  UPDATE_CART: 'UPDATE_CART',
  UPDATE_WISHLIST: 'UPDATE_WISHLIST',
  UPDATE_PAGINATION: 'UPDATE_PAGINATION',
  ADD_ADDRESS: 'ADD_ADDRESS',
  EDIT_ADDRESS: 'EDIT_ADDRESS',
  DELETE_ADDRESS: 'DELETE_ADDRESS',
  DELETE_ALL_ADDRESS: 'DELETE_ALL_ADDRESS',
  // ADD_ORDER: 'ADD_ORDER',
};

export const FILTERS_ACTION = {
  GET_PRODUCTS_FROM_PRODUCT_CONTEXT: 'GET_PRODUCTS_FROM_PRODUCT_CONTEXT',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  CHECK_CATEGORY: 'CHECK_CATEGORY',
  APPLY_FILTERS: 'APPLY_FILTERS',
  UPDATE_SEARCH_FILTER: 'UPDATE_SEARCH_FILTER',
};
