export const PRODUCTS_ACTION = {
  GET_ALL_PRODUCTS_BEGIN: 'GET_ALL_PRODUCTS_BEGIN',
  GET_ALL_PRODUCTS_FULFILLED: 'GET_ALL_PRODUCTS_FULFILLED',
  GET_ALL_PRODUCTS_REJECTED: 'GET_ALL_PRODUCTS_REJECTED',
};
