export const PRODUCTS_ACTION = {
  GET_ALL_PRODUCTS_BEGIN: 'GET_ALL_PRODUCTS_BEGIN',
  GET_ALL_PRODUCTS_FULFILLED: 'GET_ALL_PRODUCTS_FULFILLED',
  GET_ALL_PRODUCTS_REJECTED: 'GET_ALL_PRODUCTS_REJECTED',
};

export const FILTERS_ACTION = {
  GET_PRODUCTS_FROM_PRODUCT_CONTEXT: 'GET_PRODUCTS_FROM_PRODUCT_CONTEXT',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  CHECK_CATEGORY: 'CHECK_CATEGORY',
  APPLY_FILTERS: 'APPLY_FILTERS',
  UPDATE_SEARCH_FILTER: 'UPDATE_SEARCH_FILTER',
};
